baseurl = "https://www.oskarlundin.com/"
title = "Oskar Lundin"
languageCode = "en-us"

# Theme to use
theme = "oskar"

# Highlighting
pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsoptions = "linenos=table"
pygmentsStyle = "vs"

# Pagination
paginate = 3
paginatePath = "page"

# Google analytics
# googleAnalytics = ""

# Copyright
copyright = "© 2019 — Oskar Lundin — All rights reserved."

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Menu
[menu]
  # Header
  [[menu.main]]
    url = "/posts/"
    name = "blog"
    weight = 1
  [[menu.main]]
    url = "/about/"
    name = "about"
    weight = 2
  [[menu.main]]
    url = "/contact/"
    name = "contact"
    weight = 3

  # Footer
  [[menu.footer]]
    url = "https://git.oskarlundin.com/"
    name = "git"
    weight = 2
  [[menu.footer]]
    url = "mailto:c.oskar.lundin@gmail.com"
    name = "mail"
    weight = 3


# Links format
[permalinks]
  posts = "/posts/:year/:month/:title/"

[params]
  # Date format (default: Jan 2, 2006)
  # datefmt  = "Jan 2, 2006"